### ISSUE TITLE
New version not fitting

### ISSUE THREAD

**Issue by ricleal** [mljs/levenberg-marquardt#14] opened 2018-02-20 14:14 UTC
With the piece of code:

```javascript
var levenbergMarquardt = require('ml-levenberg-marquardt');

function linearFit(m, b) { return (t) => (m * t + b); }

var data = {
  x : [
    0.005, 0.01,  0.015, 0.02,  0.025, 0.03,  0.035, 0.04,  0.045,
    0.05,  0.055, 0.06,  0.065, 0.07,  0.075, 0.08,  0.085, 0.09,
    0.095, 0.1,   0.105, 0.11,  0.115, 0.12,  0.125, 0.13,  0.135,
    0.14,  0.145, 0.15,  0.155, 0.16,  0.165, 0.17,  0.175
  ],
  y : [
    1.059053, 0.820483, 0.889606, 0.695512, 0.578699, 0.527058, 0.541055,
    0.585198, 0.484689, 0.513663, 0.412635, 0.380731, 0.351293, 0.324131,
    0.29907,  0.271001, 0.25461,  0.234924, 0.21676,  0.216298, 0.184536,
    0.177404, 0.145856, 0.124078, 0.121299, 0.123407, 0.126478, 0.110142,
    0.096938, 0.091407, 0.086616, 0.076146, 0.072392, 0.071292, 0.060748
  ]
};

const options = {
  damping : 1.5,
  initialValues : [ -4, 1 ],
  gradientDifference : 10e-2,
  maxIterations : 100,
  errorTolerance : 10e-3
};

var result = levenbergMarquardt(data, linearFit, options);
console.log(result)
```

I can get results on version `1.0.0` but not on `1.0.3`.

Here the console:

```
$ npm install ml-levenberg-marquardt@v1.0.0
$ node test_ml-levenberg-marquardt_scores.js
{ parameterValues: [ -4.657817398705011, 0.7427804713876188 ],
  parameterError: 2.7274169650416935,
  iterations: 100 }

$ npm install ml-levenberg-marquardt@v1.0.3
$ node test_ml-levenberg-marquardt_scores.js
{ parameterValues: [ NaN, NaN ],
  parameterError: NaN,
  iterations: 100 }

$ npm --version
5.6.0
$ node --version
v9.5.0
```

Anything that I'm doing wrong?
Please let me know
Thanks

**Comment by targos** [comment] 2018-02-20 14:16
@maasencioh can you take a look? There should be no difference in behavior between 1.0.0 and 1.0.3

**Comment by jacobq** [comment] 2018-10-17 14:42
@ricleal The problem is that your fitting function is taking `a, b` instead of `[a, b]` for its arguments. I think the changed happened in c4c0dece02a24cc380d6e004aaec7528a9434978. I'm not sure why an API breaking change was allowed without bumping the major version, and am sorry for the inconvenience. My guess is that the API was still being decided so v1.0.0 was more like a pre-release/beta.

BTW, there are simpler/faster methods of fitting linear functions (e.g. [OLS](https://en.wikipedia.org/wiki/Ordinary_least_squares), [Simplex](https://en.wikipedia.org/wiki/Simplex_algorithm), [etc.](https://en.wikipedia.org/wiki/Linear_programming#Algorithms)), so if that's all you need to do you might be better off with one of those.

**Comment by ricleal** [comment] 2018-10-17 15:41
@jacobq  From:
```js
function linearFit(m, b) { return (t) => (m * t + b); }
```
to:
```js
function linearFit([m, b]) { return (t) => (m * t + b); }
```
solved the problem indeed!
Thanks!

**Comment by jacobq** [comment] 2018-10-17 16:07
Glad I could help. If the problem is solved for you would you mind closing the issue?

As for "uncertainties", perhaps you could open a new issue detailing that feature request.

**Closed** 2018-10-17 16:09 UTC
